### ISSUE TITLE
[ADD] HomeView 구현

### ISSUE THREAD

**Issue by KimDaeSeong8721** [KimDaeSeong8721/ShowCombine#1]
## 💡 Issue

- HomView의 UI디자인 및 기능 구현하기

## 📝  todo

- [x] 탭뷰 구현하기
- [x] 홈화면 디자인 구현하기
- [x] sheet 기능 구현하기
- [x] 페이지 슬라이드 기능 구현하기
