### ISSUE TITLE
[ADD] 딕셔너리뷰 구현하기

### ISSUE THREAD

**Issue by KimDaeSeong8721** [KimDaeSeong8721/ShowCombine#2]
## 💡 Issue

- 딕셔너리뷰 디자인 및 기능 구현하기
## 📝  todo

- [x] 수평 스크롤 뷰 구현하기
- [ ] 검색 기능 구현하기
- [x] 딕셔너리/CoreConcept 뷰 구현하기
- [ ]  딕셔너리/AsyncAPI 뷰 구현하기 !!! 
- [ ] 코드 복사기능 구현하기
