### ISSUE TITLE
[ADD] 리뷰페이지 구현하기

### ISSUE THREAD

**Issue by KimDaeSeong8721** [KimDaeSeong8721/ShowCombine#3]
## 💡 Issue

- ReviewView 디자인 및 기능 구현하기
## 📝  todo

- [x] 애플워치 디자인 구현하기
- [x]  버블 탭할 때 색 변화 기능 구현하기
- [x]  색깔이 변한 cell들의 값들 Appstorage에 저장하기 !!
